### 000 Status check
GET {{baseUrl}}/health


### 010 Register new user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Maksim Spine",
    "email": "{{email}}",
    "password": "{{password}}"
}

### 020 Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}


### 040 Post new receipts
POST {{baseUrl}}/receipts
Authorization: Bearer {{token}}
Content-Type: image/jpeg

< .attachments/IMG_20241213_180745441.jpg
